services:
  api:
    build: .
    container_name: desafio-hackaton
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      API_SECURITY_TOKEN_SECRET: ${API_SECURITY_TOKEN_SECRET}


    networks:
      - backend
    restart:
      on-failure
    volumes:
      - ./logs:/app/logs
  database:
    image: postgres:latest
    container_name: desafio-hackaton-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - backend

volumes:
  pgdata:
networks:
  backend:
    driver: bridge