spring:
  application:
    name: desafio-hackaton

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration # Local padrão para seus scripts de migração
    # clean-disabled: true # Recomendado em produção para evitar drops acidentais
    baseline-on-migrate: true # Útil se você tiver um banco de dados existente

  jackson:
    time-zone: America/Sao_Paulo
    locale: pt-BR

  cache:
    type: redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    timeout: 2000

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics
        base-path: /actuator
        cors:
          allowed-origins: "*"
    endpoint:
      health:
        show-details: always
        probes:
          enabled: true
        group:
          readiness:
            include: db,redis
          liveness:
            include: ping
    health:
      redis:
        enabled: true
      db:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true

server:
  port: 8080

jwt:
  secret: ${API_SECURITY_TOKEN_SECRET}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
