spring:
  application:
    name: desafio-hackaton

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jackson:
    time-zone: America/Sao_Paulo
    locale: pt-BR

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      connect-timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      repositories:
        enabled: true

  cache:
    type: redis
    redis:
      time-to-live: 600000ms
      cache-null-values: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
      cors:
        allowed-origins: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: db,redis
        liveness:
          include: ping
  health:
    redis:
      enabled: true
    db:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

server:
  port: 8080

jwt:
  secret: ${API_SECURITY_TOKEN_SECRET}

encryption:
  password: ${ENCRYPTION_PASSWORD:mySecretPassword123!@#}
  salt: ${ENCRYPTION_SALT:mySaltValue456$%^}

logging:
  level:
#    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
